name: simple Build

on:
  push:
    branches: master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
      
    - name: Navigate to Workspace
      run: pwd; dir; cd WCFService\projectData
    - name: Restore Packages
      run: nuget restore WCFService.sln

    - name: Build Solution
      run: |
        msbuild.exe WCFService.sln /nologo /nr:false /p:platform="Any CPU" /p:configuration="Release"
